version: '3'
services:

  #PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel/app
    container_name: PB-V1_app
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www:delegated
      - ./docker_config_files/php/local.ini:/usr/local/etc/php/conf.d/local.ini:delegated
      - ~/.composer/docker-cache/:/root/.composer:cached
    networks:
      - app-network

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: PB-V1_webserver
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www:delegated
      - ./docker_config_files/nginx/conf.d/:/etc/nginx/conf.d/:delegated
    networks:
      - app-network
    depends_on:
      - app

    #composer
  composer:
    image: composer:latest
    container_name: PB-V1_composer
    volumes:
      - ./:/var/www/
    working_dir: /var/www/
    depends_on:
      - app
    networks:
      - app-network

  #npm
  npm:
    image: node:13.7
    container_name: PB-V1_npm
    volumes:
      - ./:/var/www/
    working_dir: /var/www/
    entrypoint: ['npm']

  #artisan
  artisan:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: PB-V1_artisan
    volumes:
      - ./:/var/www
    depends_on:
      - postgres
    working_dir: /var/www/
    entrypoint: ['php', '/var/www/artisan']
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge

#Volumes
volumes:
  redis:
    driver: local
